baseURL = "www.neustatus.com"
languageCode = "en-us"
title = "Neustadtus Consulting"
themesDir = "themes"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Beth Neustadt, MBA, PhD"
    meta_og_title = "Principal and Founding Director"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.com"
    meta_og_image = "https://picsum.photos/640/360"
    meta_og_description = "Enabling clients to achieve their aims through effective diagnosis and focused individual, team and organization-wide interventions."

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"