# Global settings applied to the whole site.  
# 
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  base    = "."
  command = "hugo"
  publish = "site/public"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "hugo production"
  [context.production.environment]

# Branch deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]
  command = "hugo staging"

